[project]
name = "shared-code-environment"
version = "0.1.0"
description = "Shared code environment for UK LISA work"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dynesty",
    "nessai",
    "astropy",
    "numpy",
    "scipy",
    "bbhx-cuda12x",
    "fastemriwaveforms-cuda12x",
    "eryn",
    "lisaconstants",
    # NOTE: fastlisaresponse needs to build from source to support GPU.
    "fastlisaresponse",
    "gbgpu-cuda12x",
    "pycbc",
    "lisaglitch",
    "pyEFPE @ git+https://github.com/gmorras/pyEFPE.git",
    "jupyter",
    "nbconvert",
    "matplotlib",
    "torch>=2.7.0",
    "cupy-cuda12x",
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "cython"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
torch = [
    { index = "pytorch-cu121" },
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

