[project]
name = "shared-code-environment"
version = "0.1.0"
description = "Shared code environment for UK LISA work"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dynesty",
    "nessai",
    "astropy",
    "numpy",
    "scipy",
    "bbhx",
    "fastemriwaveforms",
    "eryn",
    "lisaconstants",
    "fastlisaresponse",
    "gbgpu",
    "pycbc",
    "lisaglitch",
    # NOTE: pyEFPE does not properly declare it needs cython. This can cause issues it's therefore not installed here, but is in the Dockerfile separately
    "pyEFPE @ git+https://github.com/spxiwh/pyEFPE.git",
    "jupyter",
    "nbconvert",
    "matplotlib",
    "torch>=2.7.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "cython"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
